### ISSUE TITLE
ユーザー登録画面ポップアップ作成

### ISSUE THREAD

**Issue by zomatype** [necocats/twitchclipper-frontend#17]
## ✨ 概要

- ログイン画面のポップアップを作成

## 🔥 ゴール

 - 入力フィールド
   - メールアドレス
   - ユーザー名
   - パスワード

## 📄 参考資料

- https://www.figma.com/design/jQZQ0gMQo0N9xMGRkNbYCf/TwitchClipper?node-id=0-1&t=TpcLYtNMTwpnfRfF-0

## ✅ タスク

- [ ] xxx

**Comment by 39rep** [comment]
これ一旦保留で
Google認証だけにする予定なのと、Google認証だけならボタン一つで完結しそう
